"use client";

import { useEffect, useMemo, useState } from "react";
import { readSupabaseTable, supabase, upsertSupabaseRow } from "./supabase";

type Access = { view: boolean; edit: boolean };
type PermissionRow = { user_id: string; email: string; display_name: string | null; role: string; permissions: Record<string, Access> };
const modules = ["Overview","Customers","Contacts","Opportunities","Projects","Suppliers","Activities","Tasks","Employees","Directory","Reports"];
const labels: Record<string,string> = { Customers:"Clients", Directory:"Settings" };

export default function PermissionsPage({announce}:{announce:(message:string)=>void}) {
  const [rows,setRows]=useState<PermissionRow[]>([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[isAdmin,setIsAdmin]=useState(false);
  const selected=useMemo(()=>rows.find(row=>row.user_id===selectedId)||rows[0], [rows,selectedId]);
  useEffect(()=>{void (async()=>{try{const session=(await supabase?.auth.getSession())?.data.session;setIsAdmin(session?.user.app_metadata?.role==="admin");const data=await readSupabaseTable<PermissionRow>("user_permissions");setRows(data);setSelectedId(data[0]?.user_id||"")}catch(error:any){announce(`Could not load permissions: ${error.message}`)}finally{setLoading(false)}})()},[announce]);
  function updateSelected(change:(row:PermissionRow)=>PermissionRow){if(!selected||!isAdmin)return;setRows(current=>current.map(row=>row.user_id===selected.user_id?change(row):row))}
  function setModule(module:string,key:keyof Access,value:boolean){updateSelected(row=>{const next={...(row.permissions?.[module]||{view:false,edit:false}),[key]:value};if(key==="edit"&&value)next.view=true;if(key==="view"&&!value)next.edit=false;return {...row,permissions:{...row.permissions,[module]:next}}})}
  async function save(){if(!selected||!isAdmin)return;setSaving(true);try{await upsertSupabaseRow("user_permissions",{...selected,updated_at:new Date().toISOString()},"user_id");announce(`Permissions saved for ${selected.email}`)}catch(error:any){announce(`Permission save failed: ${error.message}`)}finally{setSaving(false)}}
  if(loading)return <article className="permissions-shell"><p>Loading user permissions...</p></article>;
  return <div className="permissions-layout"><aside className="permissions-users"><div className="permissions-list-head"><span>USERS</span><strong>{rows.length}</strong></div>{rows.map(row=><button key={row.user_id} className={selected?.user_id===row.user_id?"active":""} onClick={()=>setSelectedId(row.user_id)}><i>{(row.display_name||row.email).slice(0,2).toUpperCase()}</i><span><strong>{row.display_name||row.email.split("@")[0]}</strong><small>{row.email}</small></span></button>)}</aside><article className="permissions-shell">{!selected?<div className="permissions-empty">No users are available yet.</div>:<><header className="permissions-header"><div><span>ACCESS PROFILE</span><h2>{selected.display_name||selected.email}</h2><p>{selected.email}</p></div><label>Role<select value={selected.role} disabled={!isAdmin} onChange={event=>updateSelected(row=>({...row,role:event.target.value}))}><option value="admin">Administrator</option><option value="manager">Manager</option><option value="user">User</option><option value="viewer">Viewer</option></select></label></header><div className="permissions-note"><strong>{isAdmin?"Administrator controls":"Read-only access"}</strong><span>{isAdmin?"Choose what this user can see and modify in every CRM module.":"Only administrators can change user permissions."}</span></div><div className="permission-matrix"><div className="permission-matrix-head"><span>Module</span><span>View</span><span>Edit</span></div>{modules.map(module=>{const access=selected.permissions?.[module]||{view:false,edit:false};return <div className="permission-row" key={module}><span><b>{module.slice(0,2).toUpperCase()}</b><strong>{labels[module]||module}</strong></span><label><input type="checkbox" checked={access.view} disabled={!isAdmin||selected.role==="admin"} onChange={event=>setModule(module,"view",event.target.checked)}/></label><label><input type="checkbox" checked={access.edit} disabled={!isAdmin||selected.role==="admin"} onChange={event=>setModule(module,"edit",event.target.checked)}/></label></div>})}</div><footer className="permissions-footer"><span>{selected.role==="admin"?"Administrators always have full access.":"Edit permission automatically includes view permission."}</span><button disabled={!isAdmin||saving} onClick={save}>{saving?"Saving...":"Save permissions"}</button></footer></>}</article></div>;
}
