"use client";

import { useEffect, useMemo, useState } from "react";
import { readSupabaseTable, supabase, upsertSupabaseRow } from "./supabase";

type Access = { view: boolean; edit: boolean };
type PermissionRow = { user_id: string; email: string; display_name: string | null; role: string; permissions: Record<string, Access> };
type EmployeeRef = { id: string; name: string; email?: string };
const modules = ["Overview","Customers","Contacts","Opportunities","Projects","Suppliers","Activities","Tasks","Employees","Directory","Reports"];
const labels: Record<string,string> = { Customers:"Clients", Directory:"Settings" };

export default function PermissionsPage({announce,employees=[]}:{announce:(message:string)=>void;employees?:EmployeeRef[]}) {
  const [rows,setRows]=useState<PermissionRow[]>([]),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[isAdmin,setIsAdmin]=useState(false);
  const selected=useMemo(()=>rows.find(row=>row.user_id===selectedId)||rows[0], [rows,selectedId]);
  const isEmployeeOnly=selected?.user_id.startsWith("employee:")??false;
  useEffect(()=>{void (async()=>{try{const session=(await supabase?.auth.getSession())?.data.session;setIsAdmin(session?.user.app_metadata?.role==="admin");const data=await readSupabaseTable<PermissionRow>("user_permissions");const employeeAccess=employees.map(employee=>({user_id:`employee:${employee.id}`,email:employee.email||`${employee.name.toLowerCase().replace(/[^a-z0-9]+/g,".").replace(/^\.|\.$/g,"")}@tps.example`,display_name:employee.name,role:"user",permissions:{}}));const employeeNames=new Set(employeeAccess.map(row=>row.display_name));const merged=[...data.filter(row=>!row.display_name||!employeeNames.has(row.display_name)),...employeeAccess];setRows(merged);setSelectedId(current=>current&&merged.some(row=>row.user_id===current)?current:merged[0]?.user_id||"")}catch(error:any){announce(`Could not load permissions: ${error.message}`)}finally{setLoading(false)}})()},[employees]);
  function updateSelected(change:(row:PermissionRow)=>PermissionRow){if(!selected||!isAdmin)return;setRows(current=>current.map(row=>row.user_id===selected.user_id?change(row):row))}
  function setModule(module:string,key:keyof Access,value:boolean){updateSelected(row=>{const next={...(row.permissions?.[module]||{view:false,edit:false}),[key]:value};if(key==="edit"&&value)next.view=true;if(key==="view"&&!value)next.edit=false;return {...row,permissions:{...row.permissions,[module]:next}}})}
  async function save(){if(!selected||!isAdmin)return;if(selected.user_id.startsWith("employee:")){announce("Create a Supabase user account for this employee before assigning permissions");return;}setSaving(true);try{await upsertSupabaseRow("user_permissions",{...selected,updated_at:new Date().toISOString()},"user_id");announce(`Permissions saved for ${selected.email}`)}catch(error:any){announce(`Permission save failed: ${error.message}`)}finally{setSaving(false)}}
  if(loading)return <article className="permissions-shell"><p>Loading user permissions...</p></article>;
  return <div className="permissions-layout"><aside className="permissions-users"><div className="permissions-list-head"><span>USERS &amp; EMPLOYEES</span><strong>{rows.length}</strong></div>{rows.map(row=><button key={row.user_id} className={selected?.user_id===row.user_id?"active":""} onClick={()=>setSelectedId(row.user_id)}><i>{(row.display_name||row.email).slice(0,2).toUpperCase()}</i><span><strong>{row.display_name||row.email.split("@")[0]}</strong><small>{row.user_id.startsWith("employee:")?"Employee · account not provisioned":row.email}</small></span></button>)}</aside><article className="permissions-shell">{!selected?<div className="permissions-empty">No users or employees are available yet.</div>:<><header className="permissions-header"><div><span>ACCESS PROFILE</span><h2>{selected.display_name||selected.email}</h2><p>{selected.email}</p></div><label>Role<select value={selected.role} disabled={!isAdmin||isEmployeeOnly} onChange={event=>updateSelected(row=>({...row,role:event.target.value}))}><option value="admin">Administrator</option><option value="manager">Manager</option><option value="user">User</option><option value="viewer">Viewer</option></select></label></header><div className="permissions-note"><strong>{isEmployeeOnly?"Employee record":isAdmin?"Administrator controls":"Read-only access"}</strong><span>{isEmployeeOnly?"Create a Supabase user account for this employee before assigning permissions.":isAdmin?"Choose what this user can see and modify in every CRM module.":"Only administrators can change user permissions."}</span></div><div className="permission-matrix"><div className="permission-matrix-head"><span>Module</span><span>View</span><span>Edit</span></div>{modules.map(module=>{const access=selected.permissions?.[module]||{view:false,edit:false};return <div className="permission-row" key={module}><span><b>{module.slice(0,2).toUpperCase()}</b><strong>{labels[module]||module}</strong></span><label><input type="checkbox" checked={access.view} disabled={!isAdmin||isEmployeeOnly||selected.role==="admin"} onChange={event=>setModule(module,"view",event.target.checked)}/></label><label><input type="checkbox" checked={access.edit} disabled={!isAdmin||isEmployeeOnly||selected.role==="admin"} onChange={event=>setModule(module,"edit",event.target.checked)}/></label></div>})}</div><footer className="permissions-footer"><span>{isEmployeeOnly?"Account provisioning is required before access can be granted.":selected.role==="admin"?"Administrators always have full access.":"Edit permission automatically includes view permission."}</span><button disabled={!isAdmin||isEmployeeOnly||saving} onClick={save}>{saving?"Saving...":"Save permissions"}</button></footer></>}</article></div>;
}
